---
title: "Study designs"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Spørsmål


I denne oppgaven skal det undersøkes hvordan ulike former for trening påvirker VO~2~maks for utrente. Det er valgt ut fem artikler som blir brukt som bakgrunn for disse undersøkelsene (Chtara, 2005; Lo et al., 2011; Nybo et al., 2010; Trapp et al., 2008; Warburton et al., 2004).<!-- Får du til å bruke referansehåndteringen som finns inbyggt i RStudio/RMarkdown? --> Ingen av disse studiene har som hovedmål å undersøke utelukkende hvordan VO~2~maks endres over en treningsperiode, men alle studiene bruker det som en del av testbatteriet sitt. Tre av studiene ser på ulike varianter av hvordan trening er helsefremmende. Nybo et al. (2010) undersøker hvordan intervalltrening og tradisjonell trening fremmer helse. Trapp et al. (2008) undersøker hvilken effekt høyintensiv intervalltrening har på fett tap og insulinverdier i hvile hos kvinner. Lo et al. (2011) undersøker hvordan trening og avtrening påvirker kroppssammensetning og fysisk prestasjon i unge menn. 

De to siste studiene hadde en litt annen tilnærming og problemstilling enn de foregående tre. Chtara et al. (2005) undersøkte samtidig styrke og utholdenhetstrenings effekt på aerob prestasjon og kapasitet. Og Warburton et al. (2004) undersøkte blod volum ekspansjon og kardiorespiratorisk funksjon.


# Alternative forklaringer

Selv om alle studiene har satt seg ut å teste forskjellige problemstillinger svarer alle til en viss grad på den problemstillingen som man prøver å besvare i denne oppgaven. Alle studiene bruker to eller flere treningsgrupper som trener forskjellig, og tester VO~2~maks før og etter, men bare Lo et al. (2010) har det med som en del av hypotesen, hvor man ønsker å undersøke endringen. Det er to av artiklene som fremstiller en hypotese (Lo et al., 2011; Warburton et al., 2004), de tre andre studiene ønsker å undersøke effekten en intervensjon har på ulike parameter.



# Metode

<!-- Denne delen kan du godt skrive mer sammen og disponere tematisk kring (1) studiedesigner og (2) statistisk metode. Forklar f.eks. hva er randomisert kontrollert studie er og hvordan den kan bli brukt for å finne ut av spørsmålene som de ulike studiene stiller.   -->

Nybø et al. (2010) brukte en randomisert kontrollstudie (RCT-studie). Gruppen som ble testet var 36 utrente menn, som ikke hadde drevet organisert fysisk aktivitet de siste to år. De hadde en gjennomsnittsalder på 31 år. Ingen av deltakerne røykte og alle var uten sykdommer. Studien sier ikke noe om hvordan dette er representativt for populasjonen. Studien bestod av 4 grupper, en gruppe som bedrev høyintensiv intervalltrening, en som trente styrketrening, en som trente moderat løping, og en kontrollgruppe. De tre treningsgruppene trente 2-3 ganger i uka i 12 uker, kontrollgruppa opprettholdt samme fysiske form som ved pre test. Alle gjennomførte testbatteriet en gang før pre test, for å bli kjent med hvordan det skulle foregå. Prestasjonstesten ble gjennomført på en standardisert tredemølle test, måling av alle de andre fysiologiske variablene ble gjennomført om morgenen i fastende tilstand. Dette ble gjennomført både før intervensjonsperioden og etter. For å sammenligne gruppene ble det brukt en to veis ANOVA test, og en veis ANOVA for å sammenligne repeterte målinger. Signifikansnivået ble satt til P \< 0,05.<!-- Hvorfor, forklar nærmere hvorfor disse testene ble brukt, hva i designet hva det som muliggjorde bruken av denne testen. -->

Trapp et al. (2008) brukte en RCT-studie. Gruppen var ikke røykende, inaktive, men friske kvinner mellom 18 og 30 år. Studien sier ikke noe om hvorvidt dette var representativt for populasjonen. Studien bestod av tre grupper, en gruppe som trente høyintensivt intervall på sykkel, en gruppe som trente moderat med kontinuerlig arbeid, og en kontrollgruppe. Det var ingen signifikante forskjeller mellom gruppene ved pretest. Både de fysiologiske testene og prestasjonstesten ble gjennomført standardisert, og det ble gjennomført pretest før intervensjonsstart og en posttest etter. De statistiske testene som ble gjennomført var en post hoc test, og det ble regnet ut en korrelasjonskoeffeisent.<!-- Samme som over: Hvorfor? -->

 

Chtara et al. (2005) brukte en RCT studie. Gruppene bestod av 48 mannlige idrettsstudenter med en gjennomsnittsalder på 21,4 år, som ikke drev med idrett utenfor studiet. Alle hadde sett protokollen, men ingen visste målet med studien. Studien bestod av fem grupper, hvor fire av dem deltok i ulike treningsprotokoller i 12 uker, og en var kontrollgruppe. En gruppe trente utholdenhet, en gruppe trente sirkel styrketrening, en gruppe trente styrke også utholdenhet, og en gruppe trente utholdenhet også styrke, dette trente de to ganger i uken. Pretestene og post testene ble gjennomført på en løpebane og i et laboratorium. Testene som ble gjennomført ute ble standardisert så godt det lar seg gjøre, men det er en del utenomliggende faktorer man ikke kan kontrollere. Laboratorium testene ble gjennomført i standardiserte forhold.  Det ble gjennomført et pre test før intervensjonen og en post test etter intervensjonen. Det ble brukt en paret t-test til å gjennomføre de statistiske analysene, og P \<0,05

 

Lo et al. (2011) gjennomførte en RCT studie. Gruppene bestod av totalt 34 friske og inaktive mannlige studenter med en snittalder på 20,4 år. De ble tilfeldig fordelt i tre ulike grupper. En gruppe trente utholdenhet 3 ganger i uka i 24 uker, en gruppe trente styrke 3 ganger i uka i 24 uker, og en gruppe var kontrollgruppe. Etter de 24 ukene med trening, hadde alle 24 uker uten trening. Det ble gjennomført tester før intervensjonsperioden, etter 24 uker, og en post test etter 48 uker. Prestasjonstestene ble gjennomført i standardiserte forhold med standardiserte protokoller enten på tredemølle eller styrke maskiner. Det samme ble de fysiologiske testene. De statistiske analysene ble gjennomført ved en veis eller to veis ANOVA. Hvor P \< 0,05.

 

Warburton et al. (2004) gjennomførte en RCT studie. Gruppene bestod av 20 normalt aktive mannlige frivillige deltakere. De ble fordelt tilfeldig i to forskjellige grupper, en gruppe som trente intervalltrening og en gruppe som trente utholdenhetstrening med kontinuerlig arbeid. Begge gruppene trente 3 dager i uka i 12 uker og hadde minimum 24 t hvile mellom hver økt. Det ble gjennomført et pre test og en post test før og etter intervensjonsperioden. Testene ble gjennomført på en standardisert måte under standardiserte forhold. De statistiske analysene som ble brukt var ANOVA, post hoc og lineær regresjon, signifikantnivået ble satt til P \< 0,05.

 

Alle studiene gjennomførte en RCT studie. Det er forskjellig antall forsøkspersoner i hver studie, men alle gruppene bestod av minst 8 personer. Ingen av studiene sier noe om hvorvidt dette er et representativt utvalg, men det er ikke noen forskjeller mellom gruppene ved pretest. Ingen av studiene sier noe om hvordan forsøkspersonene ble rekruttert, men alle forsøkspersonene har gitt samtykke til å være med, så de deltar frivillig. Det er ikke skrevet noe om sample size i noen av de fem studiene. I de aller fleste studiene ble det brukt ANOVA test for å analysere resultatene, og signifikansnivået ble oppgitt i P-verdi. Kun en av studiene hadde med VO~2~maks i hypotesen sin, men alle oppgavene svarer på hvorvidt VO~2~maks blir påvirket av intervensjonsperioden. Alle studiene svarer og på sin egen problemstilling gjennom å sammenligne pre og post verdier, og analysere endringen.

 

# Resultat

 

Alle studiene svarer på sin egen problemstilling, og tester de variablene som inngår i hypotesen eller problemstillingen. De tester og andre variabler som for eksempel VO~2~maks, som i 4 av 5 studier ikke inngår i hypotesen. Dette er typisk for idrettsforskning, hvor man gjerne har så store testbatterier at man og finner andre resultater som man egentlig ikke leter etter<!-- Referanse på det? Muligens en observasjon du kan gjennomføre på bakgrunn av presenterte studier -->. Disse blir gjerne brukt videre i andre artikler eller brukt som grunnlaget for ny forskning. Dette gjør og at man kan gjøre som det blir gjort i denne oppgaven, og se på hvordan ulik intervensjon påvirker VO~2~maks, selv om det ikke er en del av hovedfunnene til noen av studiene man bruker.

 

# Interferens

 

Alle studiene konkluderte med at de hadde funnet ut at hypotesen var delvis eller helt rett. Alle studiene konkluderte med at den gruppa som hadde trent høyintensivt eller hadde trent styrke hadde den beste helseeffekten, det var ikke alle de testede variablene man fikk signifikante funn, men man fikk uten unntak størst økning i VO~2~maks på den gruppa som hadde trent intervalltrening. Det var kun Lo et al (2011) som konkluderte med hvilken praktisk betydning funnene deres kunne ha for resten av befolkningen. Alle de andre studiene konkluderte med om man hadde svart på hypotesen eller problemstillingen sin.

# Kilder

 

 

Chtara, M. (2005).
Effects of intra-session concurrent endurance and strength training sequence on
aerobic performance and capacity. *British Journal of Sports Medicine*, *39*(8),
555--560. <https://doi.org/10.1136/bjsm.2004.015248>

Lo, M. S., Lin, L. L. C., Yao, W.-J., & Ma, M.-C. (2011). Training
and Detraining Effects of the Resistance vs. Endurance Program on Body
Composition, Body Size, and Physical Performance in Young Men. *Journal of
Strength and Conditioning Research*, *25*(8), 2246--2254.
<https://doi.org/10.1519/JSC.0b013e3181e8a4be>

Nybo, L., Sundstrup, E., Jakobsen, M. D., Mohr, M., Hornstrup, T.,
Simonsen, L., Bülow, J., Randers, M. B., Nielsen, J. J., Aagaard, P., &
Krustrup, P. (2010). High-Intensity Training versus Traditional Exercise
Interventions for Promoting Health. *Medicine & Science in Sports &
Exercise*, *42*(10), 1951--1958.
<https://doi.org/10.1249/MSS.0b013e3181d99203>

Trapp, E. G., Chisholm, D. J., Freund, J., & Boutcher, S. H. (2008).
The effects of high-intensity intermittent exercise training on fat loss and
fasting insulin levels of young women. *International Journal of Obesity*,
*32*(4), 684--691. <https://doi.org/10.1038/sj.ijo.0803781>

Warburton, D. E. R., Haykowsky, M. J., Quinney, H. A., Blackmore, D.,
Teo, K. K., Taylor, D. A., Mcgavock, J., & Humen, D. P. (2004). Blood
Volume Expansion and Cardiorespiratory Function: Effects of Training Modality: *Medicine
& Science in Sports & Exercise*, *36*(6), 991--1000.
<https://doi.org/10.1249/01.MSS.0000128163.88298.CB>
